image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - ".cache/pip"
  - venv/

before_script:
- python -V
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate

# Build package 
build:
  stage: build
  script:
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

# Run linting and test suite
test:
  stage: test
  script:
  - pip install .[test]
  - tox -e lint
  - tox

# Run security scanning 
sast:
  stage: test

stages:
- build
- test

include:
- template: Security/SAST.gitlab-ci.yml
