image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - ".cache/pip"
  - venv/

before_script:
- python -V
- pip install --upgrade pip
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate

# Build package
build_bdist:
  stage: build
  script:
  - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

# Run linting and test suite
test:
  stage: test
  script:
  - pip install .[test]
  - tox -e lint
  - tox

stages:
- build
- test
- deploy

deploy_gitlab_pypi:
  stage: deploy
  script:
  - pip install twine
  - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
  - tags
  dependencies:
  - build_bdist
